### ISSUE TITLE
Fixes for common issues

### ISSUE THREAD

**Issue by tushdante** [EricJMarti/inventory-hunter#124]
Hey all,

Leaving some feedback here from some learnings I've had deploying to azure and playing around with the configs. Along with the fix for an error I've seen reported a few times (e.g., #120) 

1. It's helpful to break out your config files by domain. So, I'm searching for a GTX3080 across newegg, bestbuy, amazon, etc. in which case I've got a separate config for each one (like `gtx3080_newegg`, `gtx3080_bestbuy`, etc.). I noticed that trying to dump all URLs into a single file would often cause the chromium driver to crash.
2. I added `self.options.add_argument('--disable-dev-shm-usage')` to the `src/driver.py` file which fixed the other issue I kept seeing (#120)
3. Adding a `docker-compose.yml` file helped as well, so I can manage all my alerters easily. See example below:

```
3080_misc:
    extends:
      file: docker-compose-common.yaml
      service: inventory_hunter
    volumes:
      - ./data/3080_misc:/data
      - ./log/3080_misc.txt:/log.txt
      - ./config/gtx3080_misc.yaml:/config.yaml
      - ./config/alerters.yaml:/alerters.yaml
    command: --alerter email --alerter-config /alerters.yaml
```

where `docker-compose-common.yaml` is 

```
version: "3"
services:
  inventory_hunter:
    build: .
```

If anyone has any suggestions to improve on my own solution I'd love to hear em. Also, huge thanks to the maintainer for setting this up!

Happy hunting everyone!
