### ISSUE TITLE
Discord mentions.

### ISSUE THREAD

**Issue by Remanent** [EricJMarti/inventory-hunter#86]
I was wondering if we could get some kind of configurable variable to allow role mentioning on discord?

https://github.com/EricJMarti/inventory-hunter/blob/1f3b91f851a6d17208e5ced7a2396c89121d1320/src/alerter.py#L78

refresh_interval: 2 # seconds
max_price: 500 # dollars/euros/etc
discord_mention: @rolegoeshere, @usergoeshere
urls:

https://discord.com/developers/docs/resources/channel#allowed-mentions-object

**Comment by EricJMarti** [comment]
Good idea. Should be fairly straightforward to implement.

**Comment by EricJMarti** [comment]
This feature has been implemented in this commit: https://github.com/EricJMarti/inventory-hunter/commit/ce807542074e981930cdb12577545f13b5307f31

To use this feature, you will need to create an alerter config: https://github.com/EricJMarti/inventory-hunter/issues/72#issuecomment-742232549

Your alerter config will look something like this:

```
---
alerters:
  discord:
    webhook_url: https://discord.com/api/webhooks/...
    mentions:
      - 12345...
      - 67890...
...
```

Each entry in the mentions section is a Discord User ID, which you can find by enabling developer mode in the app: https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID
